# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
orbs:
  android: circleci/android@2.2.0

# References are blocks of configurations that we can reference and reuse.
references:

  executor: &executor
    name: android/android-machine
    resource-class: large
    tag: 2021.10.1
  # Workspaces represent the spaces we work on & are useful for sharing data between jobs.
  # Create a workspace with the ~/code directory.
  workspace: &workspace
               ~/code

  # ---------------------------------------------------------------------------------------------------------------------
  # DECODE FIREBASE GOOGLE_SERVICE_JSON FILE AND WRITE IT TO A FILE
  # ---------------------------------------------------------------------------------------------------------------------
  decode_firebase_google_services_key: &decode_firebase_google_services_key
    run:
      name: Decode Google Firebase Services JSON key
      command: echo $FIREBASE_SECRET > app/google-services.json

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    # These next lines define the Android machine image executor: https://circleci.com/docs/2.0/executor-types/
    executor: *executor

    steps:
      # Checkout the code as the first step.
      - checkout
      - *decode_firebase_google_services_key

      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
                avd-name: myavd
                no-window: true
                restore-gradle-cache-prefix: v1a

      - android/run-tests
      - android/save-gradle-cache:
                cache-prefix: v1a

      # And finally run the release build
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease countReleaseBundleDexMethods

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path:  app/build/outputs/dexcount
          destination: dexcount
      - store_artifacts:
          path:  app/build/outputs/apk
          destination: apk

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample:
    jobs:
      - build-and-test